package com.vegasega.hrms.models.leave.viewLeave

data class EmployeeDetail(
    val address: String,
    val birth_place: Any,
    val blood_group: Any,
    val country_of_birth: String,
    val created_at: String,
    val cv: String,
    val date_of_birth: String,
    val e_mobile: String,
    val email: String,
    val employee_id: Int,
    val father_name: String,
    val gender: String,
    val gpa: Any,
    val id: Int,
    val identity_number: String,
    val last_education: Any,
    val marriage_anniversary: Any,
    val mother_name: Any,
    val name: String,
    val nationality: Any,
    val p_email: String,
    val pan_number: String,
    val permanent_address: String,
    val phone: String,
    val photo: String,
    val previous_employee_details: Any,
    val spouse_name: Any,
    val uan_no: String,
    val updated_at: String,
    val work_experience_in_years: Any
)